version: 2
updates:
  # Only check for Ruby gem updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
 'ecurity network protocol automatic matrix potocol network "
